<template>
  <h2>ClimateIQ Privacy Notice</h2>

  <p>
    This privacy notice describes how <strong>ClimateIQ</strong> collects and
    processes personal data about you through
    <a href="https://climateiq.org/">https://climateiq.org/</a>
    and all other ClimateIQ websites and mobile applications that link to this
    notice (the “Services”); how we use, store, transfer, and protect this
    personal data; and your rights in relation to this personal data. This
    notice applies to ClimateIQ, with global headquarters at 79 5th Avenue, 16th
    Floor, New York, NY 10011 USA.
  </p>
  <p>
    This privacy notice applies to all personal data we collect or process about
    you, including from you directly (e.g., when you contact us by email or
    request information through our website), data we generate about you in the
    course of our relationship with you (e.g., data collected from cookies and
    other similar technologies as described below) and data we collect about you
    from other sources, including commercially available sources, such as public
    databases (where permitted by law).
  </p>
  <p>
    Some ClimateIQ applications may include forms used to collect information
    from users. To the extent that you choose to submit information through
    these forms, there may be other privacy notices that apply to you.
  </p>
  <h3>1. Personal data we collect and use</h3>

  <p>
    We collect and use certain personal data about you. Personal data is
    information about you through which you can be identified (including where
    you can be identified by combining the information with other information).
  </p>
  <p>
    Note that we may be required by law to collect certain personal data about
    you, or as a consequence of any contractual relationship we have with you.
    Failure to provide this information may prevent or delay the fulfillment of
    our obligations to you. We will inform you at the time your personal data is
    collected whether certain data is compulsory and the consequences of the
    failure to provide such personal data.
  </p>
  <h4>1.1 Personal data we collect directly from you</h4>

  <p>
    Personal data that is collected directly from you includes the following:
  </p>
  <ol>
    <li>Personal details, such as your name(s), affiliation, and location;</li>
    <li>
      Contact details, such as your phone number, personal email address,
      mailing address, and social media handles;
    </li>
    <li>
      Authenticating information, such as user names, passwords, and security
      questions and answers;
    </li>
    <li>
      Communications, such as when you participate in message boards or forums,
      participate in polls or surveys, write a review, or contact us with a
      question, comment, or request;
    </li>
    <li>Information about your current interests and preferences.</li>
  </ol>

  <h4>1.2 Personal data generated by us</h4>

  <p>
    In addition, the following categories of personal data about you may be
    generated <span style="text-decoration: underline">by ClimateIQ</span> in
    the context of your use of the Services:
  </p>
  <ol>
    <li>Records of our interactions with you; and</li>
    <li>
      Internal notes, including notes about your inquiry into our programs and
      services.
    </li>
  </ol>

  <h4>
    1.3 Personal data we automatically collect about your use of the Services
  </h4>

  <p>
    We may also
    <span style="text-decoration: underline">automatically collect</span> the
    following categories of personal data from you over time and across
    different websites when you use the Services, including through the use of
    “cookies,” which are small text files that the Services save on your
    computer using your web browser and access when you return:
  </p>
  <ol>
    <li>
      Information about your computer and other devices, including your IP
      address, MAC address, and information about your browser and operating
      system;
    </li>
    <li>
      Information about your usage of our Services, such as the pages you visit
      when using the Services, the search terms you enter on the Services, how
      often you use the Services, and the pages you access before and after
      accessing the Services; and
    </li>
    <li>
      Data that we generate about you as a result of your use of the Services,
      such as our understanding of your interests as a result of your use of the
      Services and whether you are a regular or occasional user of the Services.
    </li>
  </ol>

  <p>
    For more information about cookies and how we use them on our websites,
    please <a href="mailto:info@climateiq.org">email us here.</a>
  </p>
  <h4>1.4 Personal data we obtain from other sources</h4>

  <p>
    ClimateIQ may also obtain the following categories of personal data about
    you <span style="text-decoration: underline">from third parties</span>:
  </p>
  <ol>
    <li>Personal details, such as name, affiliation, and location;</li>
    <li>
      Contact details, phone number, personal email address, mailing address,
      and social media handles;
    </li>
    <li>Information about your current interests and preferences; and</li>
    <li>
      Details about advertising preferences, such as products purchased or
      interaction with advertisements online.
    </li>
  </ol>

  <h3>
    <strong
      >2. How we use your personal data and the basis on which we use it</strong
    >
  </h3>

  <p>We use your personal data for the following purposes:</p>
  <ul>
    <li>
      Identification and authentication. We use your identification information
      to verify your identity when you access and use our Services and to ensure
      the security of your personal data. This is so we can comply with our
      contractual obligations to you.
    </li>
    <li>
      Operating the Services. We process your personal data to provide the
      Services you have requested. This is so we can comply with our contractual
      obligations to you.
    </li>
    <li>
      Improving our Services. We analyze information about how you use our
      Services to provide an improved experience for users of all our Services,
      including product testing and site analytics. It is in our legitimate
      business interests to use the data provided to us for this purpose, so we
      can understand any issues with our Services and improve them.
    </li>
    <li>
      Communicating with you. We use your personal data when we communicate with
      you, for example, if we are providing information about changes to the
      terms and conditions; if you contact us with questions about the Services;
      or for sending you ClimateIQ newsletters and publications. It is in our
      legitimate interests that we are able to provide you with appropriate
      responses and provide you with notices about our Services. Where required
      by law we will obtain your consent before sending you marketing
      communications.
    </li>
    <li>
      Marketing. We do not sell, rent, or lease your contact data or lists to
      third parties, and we will not provide your personal information to any
      third party individual, government agency, or company at any time unless
      compelled to do so by law. We use your personal data to build a profile
      about you and your location in order to understand your preferences better
      and to appropriately personalize information and relevant communications
      we send to you. Where required by law we will obtain your consent before
      sending such marketing messages.
    </li>
    <li>
      Complying with legal obligations. We process your personal data to comply
      with legal obligations to which we are subject, including to defend your
      and our rights in legal proceedings and to cooperate with regulators, law
      enforcement, and governmental or other competent bodies. This processing
      is necessary to comply with legal obligations and to serve our legitimate
      interests in complying with the laws to which we are subject.
    </li>
    <li>
      Customizing your experience. When you use the Services, we use your
      personal data to improve your experience of the Services, such as by
      providing interactive or personalized elements on the Services and
      providing you with content based on your interests. It is in our
      legitimate interests to provide you with a customized experience.
    </li>
    <li>
      Keeping our records accurate and up-to-date. This processing is necessary
      to comply with legal obligations and to serve our legitimate interests in
      efficient management and administration.
    </li>
  </ul>

  <p>
    We may also anonymize your personal data in such a way that you may not
    reasonably be re-identified by us or any other party, and we may use this
    anonymized information for any purpose.
  </p>
  <h3>3. Who has access to your personal data</h3>

  <p>
    We treat your personal data with care and confidentiality. Your personal
    data will be available for the purposes mentioned above and only to
    employees on a need to know basis and to the extent reasonably necessary to
    perform their functions. We may share your personal data with third parties
    under the following circumstances:
  </p>
  <ul>
    <li>
      <span style="text-decoration: underline"
        >Service providers and business partners.</span
      >
      We may share your personal data with our service providers and academic or
      business partners that perform services for us. For example, we may
      partner with other companies or entities to process secure payments,
      fulfill orders, optimize services, serve online behavioral advertising,
      send newsletters and marketing messages, support email and messaging
      services, and analyze information. These service providers and business
      partners include advertising agencies and fraud prevention agencies which
      will use your personal data only in the ways described in this policy.]
    </li>
    <li>
      <span style="text-decoration: underline"
        >Law enforcement agencies, courts, regulators, government authorities,
        or other third parties.</span
      >
      We may share your personal data with these parties where we believe this
      is necessary to comply with a legal or regulatory obligation, or otherwise
      to protect our rights or the rights of any third party.
    </li>
  </ul>

  <p>
    Because we operate internationally, the recipients referred to above may be
    located outside the jurisdiction in which you are located (or in which we
    provide the services). See the section on “International transfer of your
    data” below for more information.
  </p>
  <h3>4. How your personal data is protected and stored</h3>

  <p>
    We implement technical and organizational measures designed to safeguard the
    personal data we process. These measures are aimed at ensuring
    the ongoing integrity and confidentiality of personal data.
  </p>
  <p>
    We will retain your personal data for as long as we have a relationship with
    you. Once our relationship with you has come to an end, we will retain your
    personal data for a period of time that enables us to:
  </p>
  <ul>
    <li>Comply with record retention requirements under applicable law;</li>
    <li>Defend or bring any existing or potential legal claims; and</li>
    <li>
      Resolve or otherwise address any complaints or queries relating to our
      service.
    </li>
  </ul>

  <h3>5. International transfer of your data</h3>

  <p>
    Your personal data may be transferred to, stored, and processed in a country
    that is not regarded as ensuring an adequate level of protection for
    personal data under the data protection laws of your locale.
  </p>
  <p>
    We have put in place appropriate safeguards (such as contractual
    commitments) in accordance with applicable legal requirements to ensure that
    your personal data is adequately protected. For more information on the
    safeguards in place, please contact us at the details below.
  </p>
  <h3>6. How to exercise your rights</h3>

  <p>
    You have certain rights regarding your personal data. You have the right to
    see the personal data ClimateIQ holds, and in some situations you have the
    right to have that personal data corrected or updated, erased, restricted,
    or delivered to you or a third party in a usable electronic format (the
    right to data portability). You may also object to how ClimateIQ uses your
    personal data if the legal basis for processing that information is our
    legitimate interest.
  </p>
  <p>
    Where we are using your personal data on the basis of your consent, you have
    the right to withdraw that consent at any time. You also have the right to
    register a complaint to the applicable supervisory data protection
    authority.
  </p>
  <h3>7. How to contact us</h3>

  <p>
    If you have questions or concerns regarding the way in which your personal
    data has been used, please contact us at info@climateiq.org or:
  </p>
  <p>
    ClimateIQ<br />

    Urban Systems Lab, The New School<br />

    79 5th Avenue, 16th Floor<br />

    New York, NY 10011 USA
  </p>
  <p>
    We are committed to working with you to obtain a fair resolution of any
    complaint or concern about your privacy.
  </p>
  <h3>8. Changes to the privacy notice</h3>

  <p>
    You may request a copy of this privacy notice from us using the contact
    details set out above. We may modify or update this privacy notice from time
    to time.
  </p>
  <p>
    Where changes to this privacy notice will have a fundamental impact on the
    nature of the processing or otherwise have a substantial impact on you, we
    will notify you of the changes and give you sufficient advance notice so
    that you have the opportunity to exercise your rights (for example, to
    object to the processing).
  </p>
</template>
